name: "ACM Github Actions CI"
on:
    pull_request:
        branches: [main, dev]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "16.14.2"
            - run: npm ci
            - run: npm run build
            - run: |
                  if: steps.wait-for-build.outputs.conclusion == 'success'; then
                    echo "Code is successfully built!"
                  else 
                    echo "Build failed!"
                  fi
